### ISSUE TITLE
Issue when leaf values in DICT_VALS are not strings

### ISSUE THREAD

**Issue by kili-mandjaro** [pappasam/latexbuild#1]
`TypeError: expected string or buffer` because function `escape_latex_str` expects a string value. What's more, Jinja2 seems to handle perfectly other types like Booleans and Numbers.

_btw: nicely useful python module ;-)_

**Comment by pappasam** [comment]
Yep, this was definitely a bug. The changes have been pushed to pypi for version 0.2.2. Hopefully this resolves the problem, and definitely let me know if it causes any problems.
