### ISSUE TITLE
Failing to produce docx file

### ISSUE THREAD

**Issue by shabbir-zinnox** [pappasam/latexbuild#10]

**Comment by pappasam** [comment]
To produce a docx file, you'll need to install the appropriate binary on your system (latex2rtf). If you're using ubuntu:

```
sudo apt install latex2rtf latex2rtf-doc
```

**Comment by shabbir-zinnox** [comment]
> To produce a docx file, you'll need to install the appropriate binary on your system (latex2rtf). If you're using ubuntu:
> 
> ```
> sudo apt install latex2rtf latex2rtf-doc
> ```

i have installed latex2rtf in my ubuntu system, but still failing to produce a docx file

**Comment by pappasam** [comment]
Ok, good to know. Please provide the files that you're converting, along with the code you're using to attempt to convert them to docx, along with your error message. It's impossible for me to help you debug more without this information.
