### ISSUE TITLE
more detail / fully working example regarding paths

### ISSUE THREAD

**Issue by drcjar** [pappasam/latexbuild#4]
Hi @pappasam this looks like just what I need but I'm struggling to get it to work out of the box.

I think it has to do with me not understanding how these paths are used.

PATH_JINJA2 = "/path/to/your/latex/jinja2/root"
PATH_TEMPLATE_RELATIVE_TO_PATH_JINJA2 = "template/filepath.tex"

Would it be possible to provide a fully working minimum example[1] please? 

1. e.g related examples in http://pythonhosted.org/latex/

**Comment by pappasam** [comment]
@drcjar Sorry for the late response! Seems this got lost in my inbox. I'm guessing you've either found a workaround or have used another tool by now, but I'll work on getting a full example uploaded to the README.

**Comment by drcjar** [comment]
thanks @pappasam I'm still v keen to try yours so if you have time to make full example that'd be awesome

**Comment by pappasam** [comment]
@drcjar I added an /examples directory with a working example. Simply run "build.py" within that directory and examine the PDF files generated within that directory's "pdf" directory. I'll try add a readme with more-clear run instructions in the future, but this should be enough of a working example to get you up and running.

**Comment by drcjar** [comment]
thanks @pappasam that's very helpful, am up and running now
