### ISSUE TITLE
Bibtex

### ISSUE THREAD

**Issue by aparrot89** [pappasam/latexbuild#7]
Hi 
How to compile file with reference from a .bib files (command \bibliographystyle{stylename} and
\bibliography{bibfilename}) ?

**Comment by pappasam** [comment]
Hmm, good question! I hadn't considered that when I wrote this library. That would require modifying the build logic in latexbuild.build.LatexBuild.run_latex. Bibtex requires running a separate executable, which isn't currently supported by this library. See this link for the relevant required commands: http://www.bibtex.org/Using/

This feature is probably outside the scope of this project. That said, if you can think of an elegant solution, I'd be happy to consider it!

**Comment by aparrot89** [comment]
I want to automate the creation of data papers.
I think I will you only use your render_latex_template function and do like https://tex.stackexchange.com/questions/204291/bibtex-latex-compiling.
Thanks a lot for your fast answer
